volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_redis_data: {}

services:
  django:
    build:
      dockerfile: ./compose/production/django/Dockerfile
    image: brain_production_django
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres

  postgres:
    image: brain_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: brain_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    volumes:
      - production_redis_data:/data

  celeryworker:
    build:
      dockerfile: ./compose/production/django/Dockerfile
    image: brain_production_celeryworker
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres

  celerybeat:
    build:
      dockerfile: ./compose/production/django/Dockerfile
    image: brain_production_celerybeat
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres

  flower:
    build:
      dockerfile: ./compose/production/django/Dockerfile
    image: brain_production_flower
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
