volumes:
  brain_local_postgres_data: {}
  brain_local_postgres_data_backups: {}
  brain_local_redis_data: {}

services:
  django:
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: brain_local_django
    container_name: brain_local_django
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'

  postgres:
    image: brain_production_postgres
    container_name: brain_local_postgres
    volumes:
      - brain_local_postgres_data:/var/lib/postgresql/18/docker
      - brain_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    container_name: brain_local_redis
    volumes:
      - brain_local_redis_data:/data

  celeryworker:
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: brain_local_celeryworker
    container_name: brain_local_celeryworker
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

  celerybeat:
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: brain_local_celerybeat
    container_name: brain_local_celerybeat
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

  flower:
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: brain_local_flower
    container_name: brain_local_flower
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '5555:5555'
