# Generated by Django 6.0.7 on 2026-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('tagline', models.CharField(blank=True, default='', max_length=300, verbose_name='tagline')),
                ('bio', models.CharField(blank=True, default='', verbose_name='bio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='portfolio/avatar', verbose_name='avatar')),
                ('resume', models.FileField(blank=True, null=True, upload_to='portfolio/resume', verbose_name='resume')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='linkedin url')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='github url')),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='category')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='location')),
                ('role', models.CharField(max_length=200, verbose_name='role')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('skills', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.skill', verbose_name='skills')),
            ],
            options={
                'verbose_name': 'work experience',
                'verbose_name_plural': 'work experiences',
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
