name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_FILE: brain/docker-compose.local.yml:brain/docker-compose.ci.yml

on:
  pull_request:
    branches: ['main']
    paths-ignore: ['docs/**']

  push:
    branches: ['main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v6

      - name: Build django image
        run: docker compose build django

      - name: Check DB Migrations
        run: docker compose run --rm django python manage.py makemigrations --check

      - name: Run DB Migrations
        run: docker compose run --rm django python manage.py migrate

      - name: Run Django Tests
        run: docker compose run django pytest

      - name: Tear down the Stack
        run: docker compose down